server:
  port: 8001

spring:
  profiles:
    active: dev
  application:
    name: campus-evaluation-service-core
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/review?serverTimezone=UTC
    username: root
    password: YuZe0703
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848   #nacos服务地址
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 20
        max-idle: 8
        min-idle: 0


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/design/cloud/core/mapper/xml/*.xml

